// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAuthTokens() {
  return window['go']['main']['App']['ClearAuthTokens']();
}

export function ConvertRawBytes(arg1, arg2) {
  return window['go']['main']['App']['ConvertRawBytes'](arg1, arg2);
}

export function ConvertRawFile(arg1) {
  return window['go']['main']['App']['ConvertRawFile'](arg1);
}

export function ExportRetouchedImage(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['ExportRetouchedImage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function ExportRetouchedImageNative(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportRetouchedImageNative'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadAuthTokens() {
  return window['go']['main']['App']['LoadAuthTokens']();
}

export function NativeRawConvertAvailable() {
  return window['go']['main']['App']['NativeRawConvertAvailable']();
}

export function SaveAuthTokens(arg1, arg2) {
  return window['go']['main']['App']['SaveAuthTokens'](arg1, arg2);
}

export function SaveRenderedImage(arg1, arg2) {
  return window['go']['main']['App']['SaveRenderedImage'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectRawFiles() {
  return window['go']['main']['App']['SelectRawFiles']();
}

export function SelectSavePath(arg1) {
  return window['go']['main']['App']['SelectSavePath'](arg1);
}
