// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportRetouchedImage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number,arg9:number,arg10:string):Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function SelectSavePath(arg1:string):Promise<string>;
